### ISSUE TITLE
Thanks for this!

### ISSUE THREAD

**Issue by NuLLFiX** [Tonny-Francis/EFI-MACHINIST-X99-P4-XEON-E5-2640-V3-RX5500XT#1]
Thanks i used your EFI for my ZSUS X99 P4 mobo from AliExpress with this CPU E5-2650 v4

It seems you didn't use internal sound card i guess its not supported.

Also my cpu is 12 core and it seems only 10 shows in hwinfo? Can this be fixed?

I made my GPU work! 6700xt got 3D ACC...

**Comment by Tonny-Francis** [comment]
Hello, yes I didn't use the internal audio card, and the settings may be different for each motherboard, compatibility may exist, just configure the sound layout, this may be useful:
https://dortania.github.io/OpenCore-Post-Install/universal/audio.html#making-layout-id-more-permanent

Regarding the CPU colors not being displayed correctly, did you see this in Windows itself using HWIFO? I haven't tested this EFI with other XEON processors, the current one used is XEON-E5-2640

**Comment by NuLLFiX** [comment]
Thanks for the sound info ill check it out... and report. If sound do not work after all i'll get a usb audio card like yours.

The cpu im using is E5-2650 v4 i got info from intel's site CPU specs its 12core/24thread XEON...

I have also dualboot with Win10 and got some special Chinese Chipset drivers for mobo that works... I'll check it there also but i think windows reports correct cores/threads for it.

**Comment by Tonny-Francis** [comment]
Hello, could you clear my doubts about how many sticks of RAM you can run on this ZSUS X99 P4 motherboard on macOS?

**Comment by NuLLFiX** [comment]
I know some saying that you run this mobos with server only mem. This is not correct i tried 2 sticks with random ddr4 rams (non server) and they worked fine... for now i'll get more ram later...

**Comment by Tonny-Francis** [comment]
I use DRR4 memory even though it's not ECC, my question is because in my combo I can't add 1 more memory stick, which leads me to believe that my motherboard has problems, thank you
